apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 9.0.0
  count: 1
  http:
    service:
      spec:
        type: NodePort
        ports:
        - port: 5601
          nodePort: 5601
          protocol: TCP
  elasticsearchRef:
    name: elasticsearch
