apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  image: quay.io/prometheus/prometheus:v3.3.0
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    requests:
      memory: 400Mi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus
  version: v3.3.0
  podMonitorSelector: {}
  probeSelector: {}
  scrapeConfigSelector: {}
  serviceMonitorSelector: {}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
    nodePort: 9090
    protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: prometheus
