apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  labels:
    prometheus: mon
spec:
  selector:
    matchLabels:
      k8s-app: node-exporter
  endpoints:
  - port: metrics
    interval: 15s
---

apiVersion: v1
kind: Service
metadata:
  name: outOfCluster
  labels:
    k8s-app: node-exporter
spec:
  type: ExternalName
  externalName: outOfCluster
  clusterIP: ""
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: 9100

---

apiVersion: v1
kind: Endpoints
metadata:
  # Name must match service name
  name: outOfCluster
  labels:
    k8s-app: node-exporter
subsets:
  - addresses:
    - ip: SCRAPE_TARGET_IP
    ports:
      - name: metrics
        port: 9100
        protocol: TCP
