---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          # env:
          #   - name: GF_SERVER_DOMAIN
          #     value: "localhost"
          #   - name: GF_SERVER_ROOT_URL
          #     value: "https://grafana.localhost:3000"
          #   - name: GF_SERVER_CERT_KEY
          #     value: "/etc/grafana/tls.key"
          #   - name: GF_SERVER_CERT_FILE
          #     value: "/etc/grafana/tls.crt"
          #   - name: GF_SERVER_ENFORCE_DOMAIN
          #     value: "False"
          #   - name: GF_SERVER_PROTOCOL
          #     value: "https"
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              # scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            httpGet:
              port: 3000
              # scheme: HTTPS
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-pv
            # - name: cert-info-volume
            #   mountPath: /etc/grafana/tls.key
            #   subPath: tls.key
            #   readOnly: true
            # - name: cert-info-volume
            #   mountPath: /etc/grafana/tls.crt
            #   subPath: tls.crt
            #   readOnly: true
      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc
        # - name: cert-info-volume
        #   secret:
        #     secretName: cert-info
        #     items:
        #       - key: tls.key
        #         path: tls.key
        #       - key: tls.crt
        #         path: tls.crt
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: http-grafana
      protocol: TCP
      nodePort: 3000
  sessionAffinity: None
  selector:
    app: grafana
