apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-mirror
spec:
  selector:
    matchLabels:
      app: docker-mirror
  template:
    metadata:
      labels:
        app: docker-mirror
    spec:
      containers:
      - name: registry
        image: registry:3
        env:
          # - name: https_proxy
          #   value: http://squid.default.svc.cluster.local:8080
          - name: REGISTRY_PROXY_REMOTEURL
            value: https://mirror.gcr.io
          - name: OTEL_TRACES_EXPORTER
            value: none
---
apiVersion: v1
kind: Service
metadata:
  name: docker-mirror
  labels:
    app: docker-mirror
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 5000
    protocol: TCP
  selector:
    app: docker-mirror
