apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-registry
spec:
  selector:
    matchLabels:
      app: image-registry
  template:
    metadata:
      labels:
        app: image-registry
    spec:
      #hostNetwork: true
      #dnsPolicy: Default
      containers:
      - name: registry
        image: registry:3
        env:
          # - name: https_proxy
          #   value: http://squid.default.svc.cluster.local:8080
          - name: OTEL_TRACES_EXPORTER
            value: none
---
apiVersion: v1
kind: Service
metadata:
  name: image-registry
  labels:
    app: image-registry
spec:
  type: NodePort
  ports:
  - port: 65000
    targetPort: 5000
    nodePort: 65000
    protocol: TCP
  selector:
    app: image-registry
