apiVersion: apps/v1
kind: Deployment
metadata:
  name: apt-cacher-ng
spec:
  selector:
    matchLabels:
      app: apt-cacher-ng
  template:
    metadata:
      labels:
        app: apt-cacher-ng
    spec:
      containers:
      - name: apt-cacher-ng
        image: localhost:65000/apt-cacher-ng:ubuntu
        volumeMounts:
        - name: apt-cacher-ng-config
          mountPath: /etc/acng.conf
          subPath: acng.conf
      volumes:
      - name: apt-cacher-ng-config
        configMap:
          name: apt-cacher-ng-config
---
apiVersion: v1
kind: Service
metadata:
  name: apt-cacher-ng
  labels:
    app: apt-cacher-ng
spec:
  type: NodePort
  ports:
  - port: 3142
    nodePort: 3142
    protocol: TCP
  selector:
    app: apt-cacher-ng
