apiVersion: v1
kind: Service
metadata:
  name: argocd-server
spec:
  type: LoadBalancer
#  loadBalancerIP: a.b.c.d
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
    nodePort: 443
